.TH sbosubmit 1

.SH NAME
.PP
\fBsbosubmit\fP \- the SlackBuilds.org submission tool


.SH SYNOPSIS
.PP
\fBsbosubmit\fP [\fBoptions\fP]


.SH DESCRIPTION
.PP
\fBsbosubmit\fP is a tool to facilitate uploading of SlackBuilds to
SlackBuilds.org. It does it by performing checks of the files to be submitted,
packaging them and then uploading the resulting tarball to the SlackBuilds.org
server for later approval.

.PP
Using traditional methods, when you want to submit a SlackBuild,
you have to perform at least the following steps:

.RS
.IP \(bu 2
very often you have to cleanup the SlackBuild directory from files used during
development stage,
.IP \(bu 2
create the archive of the files to be submitted,
.IP \(bu 2
open web browser,
.IP \(bu 2
attach the archive,
.IP \(bu 2
fill in all the submission details,
.IP \(bu 2
press the submit button,
.IP \(bu 2
very often delete the created archive.

.RE

.PP
\fBsbosubmit\fP allows you to perform all these steps (and a bit more) by typing
a single command from within the SlackBuild directory. If you use the proposed
\fItmpdir\fP directory for additional development files (e.g. extracted source
tarball), then you don't have to cleanup anything before the submission:
\fItmpdir\fP is skipped when \fBsbosubmit\fP creates the submission archive.
Read on to learn more.

.PP
Before using the tool, familiarize yourself with the submission guidelines
available from 
\[la]https://slackbuilds.org/guidelines/\[ra]\&. Keep in mind that this tool
has been created to facilitate the submission and not to make the life of
the SlackBuilds.org maintainers harder than it already is.
\fBALWAYS DOUBLE CHECK\fP your submission before proceeding. Although the author
of the tool paid a lot of attention to code different checks of the files being
submitted, it is you who is responsible for making sure the files are
the correct ones.

.PP
For proper operation, \fBsbosubmit\fP expects certain directory structure to work
with, namely the one that is used by \fBsbopkg\fP and SlackBuilds.org itself.
This means that you have to keep the SlackBuilds organized in the
\fB\fCCATEGORY/PRGNAM\fR fashion. Only the \fB\fCCATEGORY/PRGNAM\fR component of the path is
important, other than that, your SlackBuilds can reside in whichever location
you want.

.PP
Example for submitting \fIlibreoffice\fP would be:

.PP
.RS

.nf
$ cd /path/to/slackbuilds/office/libreoffice
$ sbosubmit

.fi
.RE

.PP
Before uploading, \fBsbosubmit\fP performs basic checks on the following files:

.RS
.IP \(bu 2
PRGNAM.SlackBuild
.IP \(bu 2
slack−desc
.IP \(bu 2
PRGNAM.info
.IP \(bu 2
README

.RE

.PP
If present in the directory, the following files/directories won't be packaged
and uploaded:

.RS
.IP \(bu 2
non−regular file except directory,
.IP \(bu 2
empty directory,
.IP \(bu 2
soft link,
.IP \(bu 2
\fItmpdir\fP directory (or regular file),
.IP \(bu 2
keywords.txt,
.IP \(bu 2
comment.txt

.RE

.PP
\fIsoft link\fP can be used to point to the program source tarball, so that
the tarball itself does not have to reside in the same directory as
the SlackBuild.

.PP
\fItmpdir\fP can be used freely during SlackBuild development, for example to
extract the program source tarball for which the SlackBuild is being written.
On my system, the backup software is configured so that it excludes \fItmpdir\fP
under my SlackBuilds repository path.

.PP
\fIkeywords.txt\fP can be used to keep the keywords for SlackBuild submission.
This file is only processed if the \fB\-\-keywords\fP option is passed to sbosubmit.
Refer to \fB\-\-keywords\fP option description for more information.

.PP
\fIcomment.txt\fP can be used to keep the comment for the SlackBuild submission.
This file is only processed if the \fB\-\-comment\fP option is passed to sbosubmit.
Refer to \fB\-\-comment\fP option description for more information.


.SH OPTIONS
.PP
\fB\-\-address\fP=\fIADDRESS\fP

.PP
Allows to specify alternative submission address, e.g. for testing purposes.
Default address is set to 
\[la]https://slackbuilds.org/\[ra]

.PP
\fB\-\-comment\fP\fI[=COMMENT]\fP

.PP
Allows to specify the comment for SlackBuild submission. If the \fICOMMENT\fP string
is omitted, the comment is taken from the \fIcomment.txt\fP file residing in
the SlackBuild directory. You should only add the comment if there's something
important about the submission that the SlackBuilds.org maintainers should be
aware of, e.g. if you are taking over the maintenance of the SlackBuild from
someone who abandoned it.

.PP
\fB\-\-email\fP=\fIEMAIL\fP

.PP
Allows to specify your e\-mail address for submission. This is required in
the absence of the environment variable \fBSBOSUBMIT\_SUBMISSION\_EMAIL\fP\&.

.PP
\fB\-\-help\fP

.PP
Display usage information and exit.

.PP
\fB\-\-keywords\fP\fI[=KEYWORDS]\fP

.PP
Allows to specify the keywords for submission. If the \fIKEYWORDS\fP string is
omitted, the keywords are taken from the \fIkeywords.txt\fP file residing in
the SlackBuild directory. Keywords are comma−separated words that help searchers
find your submission. Note:

.RS
.IP \(bu 2
if you are submitting a version update, don't pass the \fB\-\-keywords\fP option,
.IP \(bu 2
if you wish to add a new keyword to the list, type only the new keyword (this
applies both to the \fIkeywords.txt\fP file and the command line supplied
keyword.)

.RE

.PP
\fB\-\-verbose\fP

.PP
Be verbose (quiet by default.)

.PP
\fB\-\-version\fP

.PP
Display version information and exit.


.SH FILE FORMATS
.PP
\fBCOMMENT\fP

.PP
Comment file is simply a text file. The text contained within the comment file
is sent \fIas is\fP\&.

.PP
\fBKEYWORDS\fP

.PP
Keywords file is a text file, where the keywords are separated by comma.
The keywords can span multiple lines, but remember that new line does not
separate the individual keywords, only comma does.


.SH ENVIRONMENT
.PP
\fBSBOSUBMIT\_SUBMISSION\_EMAIL\fP

.PP
Your e\-mail address as expected by SlackBuilds.org submission process.

.PP
\fBSBOSUBMIT\_INFO\_MAINTAINER\fP

.PP
The name that you put into \fIMAINTAINER\fP field of the \fI\&.info\fP file of
the submission. This value is only used to check if what you put into \fI\&.info\fP
file is correct \- if this value is empty, the check is not performed.

.PP
\fBSBOSUBMIT\_INFO\_EMAIL\fP

.PP
The e−mail address that you put into \fIEMAIL\fP field of the \fI\&.info\fP file of
the submission (some people prefer to put obfuscated e\-mail there, so it's
different from \fBSBOSUBMIT\_SUBMISSION\_EMAIL\fP, which has to be your real working
address.) This value is only used to check if what you put into \fI\&.info\fP file is
correct \- if this value is empty, the check is not performed.


.SH BUGS
.RS
.IP \(bu 2
If the submission is interrupted during the transfer to the server,
the temporary file \fI/tmp/sbosubmit.XXX\fP is not being removed.

.RE


.SH AUTHOR
.PP
Andrzej Telszewski <andrzej@telszewski.com>


.SH SEE ALSO
.PP
\fBslackpkg\fP(8), \fBsbopkg\fP(8), \fBslackrepo\fP(8).
